Repository vertica/VerticaPy, pull requests merged in 2022-09, with the labels that each got.

#362 Bug Corrections + New Methods for iForest
  setup.py
  verticapy/__init__.py
  verticapy/learn/ensemble.py
  verticapy/learn/vmodel.py
  verticapy/tests/sql/test_sql.py
  verticapy/tests/vModel/test_iforest.py
  verticapy/utilities.py
  verticapy/vdataframe.py
Labels: enhancement

#364 Using Vertica-CE docker image for testing
  .github/workflows/ci.yaml
Labels: Test

#365 Uploaded the Cheat Sheet for Verticapy
  cheat_sheet/VerticaPy Machine Learning Cheat Sheet.docx
  cheat_sheet/VerticaPy Machine Learning Cheat Sheet.pdf
Labels: documentation
