Repository vertica/VerticaPy, pull requests merged in 2022-11, with the labels that each got.

#389 VMAP AND COMPLEX DATA TYPE SUPPORT
  setup.py
  verticapy/__init__.py
  verticapy/data/laliga/2004.json
  verticapy/data/laliga/2005.json
  verticapy/data/laliga/2006.json
  verticapy/data/laliga/2007.json
  verticapy/data/laliga/2008.json
  verticapy/data/laliga/2009.json
  verticapy/data/laliga/2010.json
  verticapy/data/laliga/2011.json
  verticapy/data/laliga/2012.json
  verticapy/data/laliga/2013.json
  verticapy/data/laliga/2014.json
  verticapy/data/laliga/2015.json
  verticapy/data/laliga/2016.json
  verticapy/data/laliga/2017.json
  verticapy/data/laliga/2018.json
  verticapy/datasets.py
  verticapy/tests/utilities/csv_many/titanic-1.csv
  verticapy/tests/utilities/csv_many/titanic-2.csv
  verticapy/tests/utilities/csv_many/titanic-3.csv
  verticapy/tests/utilities/json_many/titanic-passengers-1.json
  verticapy/tests/utilities/json_many/titanic-passengers-2.json
  verticapy/tests/utilities/test_utilities.py
  verticapy/tests/vDataFrame/test_vDF_create.py
  verticapy/toolbox.py
  verticapy/utilities.py
  verticapy/vcolumn.py
  verticapy/vdataframe.py
Labels: new feature

#403 Improving read_csv, read_json and read_file
  verticapy/learn/tools.py
  verticapy/tests/sql/test_sql.py
  verticapy/tests/utilities/test_utilities.py
  verticapy/tests/vDataFrame/test_vDF_utilities.py
  verticapy/utilities.py
  verticapy/vcolumn.py
  verticapy/vdataframe.py
Labels: enhancement

#406 Adding complex datatype parameter for read_json
  verticapy/utilities.py
Labels: enhancement

#408 Support of to_db for flex
  verticapy/tests/utilities/test_utilities.py
  verticapy/vdataframe.py
Labels: enhancement

#409 Jaro Winkler + vdf.join
  verticapy/stats/math.py
  verticapy/tests/sql/test_sql.py
  verticapy/tests/stats/test_stats.py
  verticapy/tests/vDataFrame/test_vDF_combine_join_sort.py
  verticapy/tests/vDataFrame/test_vDF_utilities.py
  verticapy/utilities.py
  verticapy/vdataframe.py
Labels: new feature

#412 read_csv new parameters
  verticapy/tests/vDataFrame/test_vDF_combine_join_sort.py
  verticapy/utilities.py
Labels: enhancement

#414 Final PR
  verticapy/tests/utilities/test_utilities.py
  verticapy/tests/vDataFrame/test_vDF_utilities.py
  verticapy/toolbox.py
  verticapy/utilities.py
  verticapy/vdataframe.py
Labels: Test

#417 Bug + Doc Correction
  verticapy/datasets.py
  verticapy/utilities.py
  verticapy/vcolumn.py
  verticapy/vdataframe.py
Labels: bug

#425 Correction of multiple small issues
  setup.py
  verticapy/__init__.py
  verticapy/toolbox.py
  verticapy/utilities.py
  verticapy/vcolumn.py
  verticapy/vdataframe.py
Labels: enhancement

#427 DBLINK - PART 1
  verticapy/__init__.py
  verticapy/connect.py
  verticapy/sql.py
  verticapy/vdataframe.py
Labels: new feature
