Repository vertica/VerticaPy, pull requests merged in 2023-12, with the labels that each got.

#966 Sphinx Docstring - Enhanced examples of vdataframe/base + _machine_learning
  verticapy/core/vdataframe/_machine_learning.py
  verticapy/core/vdataframe/base.py
Labels: Documentation

#968 Sphinx docstring changes for parser/pandas
  verticapy/core/parsers/pandas.py
Labels: Documentation

#971 Formatting correctly memmodels
  verticapy/machine_learning/memmodel/base.py
  verticapy/machine_learning/memmodel/cluster.py
  verticapy/machine_learning/memmodel/decomposition.py
  verticapy/machine_learning/memmodel/ensemble.py
  verticapy/machine_learning/memmodel/linear_model.py
  verticapy/machine_learning/memmodel/naive_bayes.py
  verticapy/machine_learning/memmodel/preprocessing.py
  verticapy/machine_learning/memmodel/tree.py
  verticapy/machine_learning/vertica/cluster.py
Labels: Documentation

#973 Sphinx Docstring - Updated formulas
  verticapy/core/vdataframe/_machine_learning.py
  verticapy/machine_learning/metrics/classification.py
  verticapy/machine_learning/metrics/regression.py
  verticapy/machine_learning/model_selection/variables_selection.py
Labels: Documentation

#974 [Docstring] Memmodel - PART 1
  verticapy/machine_learning/memmodel/base.py
  verticapy/machine_learning/memmodel/cluster.py
  verticapy/machine_learning/memmodel/decomposition.py
  verticapy/machine_learning/memmodel/ensemble.py
  verticapy/machine_learning/memmodel/linear_model.py
  verticapy/machine_learning/memmodel/naive_bayes.py
  verticapy/machine_learning/memmodel/preprocessing.py
  verticapy/machine_learning/memmodel/tree.py
Labels: Documentation

#969 [Docstring] kmeans + misc
  verticapy/core/vdataframe/_machine_learning.py
  verticapy/machine_learning/model_selection/kmeans.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/decomposition.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/feature_extraction/text.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/naive_bayes.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/preprocessing.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/machine_learning/vertica/tsa.py
  verticapy/sql/flex.py
  verticapy/sql/functions/regexp.py
  verticapy/sql/geo/functions.py
  verticapy/sql/geo/index.py
  verticapy/sql/insert.py
Labels: Documentation

#976 [Docstring] Memmodel + Misc
  verticapy/core/vdataframe/_pivot.py
  verticapy/machine_learning/memmodel/cluster.py
  verticapy/machine_learning/memmodel/ensemble.py
  verticapy/machine_learning/memmodel/tree.py
  verticapy/machine_learning/model_selection/model_validation.py
  verticapy/machine_learning/vertica/automl/clustering.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/svm.py
Labels: Documentation

#978 [Docstring] model_validation + misc
  verticapy/machine_learning/model_selection/hp_tuning/cv.py
  verticapy/machine_learning/model_selection/model_validation.py
  verticapy/machine_learning/vertica/automl/dataprep.py
  verticapy/machine_learning/vertica/automl/supervised.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/decomposition.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/feature_extraction/text.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/naive_bayes.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/preprocessing.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/machine_learning/vertica/tsa.py
Labels: Documentation

#988 Sql magic correction + MISC
  verticapy/core/tablesample/base.py
  verticapy/core/vdataframe/_read.py
  verticapy/core/vdataframe/base.py
  verticapy/jupyter/extensions/sql_magic.py
  verticapy/machine_learning/model_selection/kmeans.py
  verticapy/performance/vertica/qprof.py
  verticapy/plotting/_plotly/pie.py
Labels: Bug, Documentation

#990 Sphinx Docstring for plot_acf_pacf
  verticapy/machine_learning/model_selection/hp_tuning/plotting.py
  verticapy/tests_new/machine_learning/vertica/conftest.py
Labels: Documentation

#993 Sphinx Docstring - adding model fit for predict function
  verticapy/machine_learning/vertica/ensemble.py
Labels: Documentation

#992 Sphinx Docstring - Added examples for functions inside decomposition.py
  verticapy/machine_learning/vertica/automl/supervised.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/decomposition.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/preprocessing.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tsa.py
Labels: Documentation

#996 Sphinx Docstring for smaller functions inside classes in machine_learning/vertica/cluster.py
  verticapy/machine_learning/model_selection/hp_tuning/plotting.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/decomposition.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/naive_bayes.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/preprocessing.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/machine_learning/vertica/tsa.py
Labels: Documentation

#995 corrections for plot_acf_pacf
  verticapy/plotting/_matplotlib/acf.py
  verticapy/plotting/base.py
Labels: Bug, Plotting - Matplotlib

#998 Docstrings for linear_models + misc
  verticapy/core/parsers/pandas.py
  verticapy/core/vdataframe/base.py
  verticapy/datasets/generators.py
  verticapy/machine_learning/metrics/classification.py
  verticapy/machine_learning/metrics/regression.py
  verticapy/machine_learning/model_selection/hp_tuning/cv.py
  verticapy/machine_learning/model_selection/hp_tuning/plotting.py
  verticapy/machine_learning/model_selection/model_validation.py
  verticapy/machine_learning/model_selection/statistical_tests/norm.py
  verticapy/machine_learning/model_selection/statistical_tests/ols.py
  verticapy/machine_learning/model_selection/statistical_tests/tsa.py
  verticapy/machine_learning/model_selection/variables_selection.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/decomposition.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/naive_bayes.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/machine_learning/vertica/tsa.py
Labels: Documentation

#997 Sphinx docstring changes for Parsers/csv
  verticapy/core/parsers/csv.py
Labels: Documentation

#1000 Docstring for Time Series.
  verticapy/machine_learning/metrics/regression.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/tsa.py
Labels: Documentation

#999 [Docstring] vertica/preprocessing
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/preprocessing.py
Labels: Documentation

#1006 json correction.
  verticapy/core/parsers/json.py
Labels: Documentation

#1007 [Docstring] VerticaModel + Regression + Unsupervised
  verticapy/core/parsers/_utils.py
  verticapy/core/parsers/json.py
  verticapy/core/vdataframe/_machine_learning.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/model_management.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/svm.py
Labels: Documentation

#1008 Adding a long version tag
  verticapy/__init__.py
Labels: Config | Utils

#1009 Sphinx Docstring machine_learning / vertica / base
  verticapy/machine_learning/vertica/base.py
Labels: Documentation

#1011 Finalising vertica/base docstrings
  verticapy/core/parsers/csv.py
  verticapy/core/parsers/json.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/linear_model.py
Labels: Documentation

#1013 Sphinx New Page - Adding Elbow Curve to the chart gallery
  docs/source/_static/pic_elbow.png
  docs/source/chart_gallery.rst
  docs/source/chart_gallery_elbow.rst
Labels: Documentation

#1012 Final docstring for ML.
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/neighbors.py
Labels: Documentation

#1014 Sphinx Style update - version boxes style changed
  docs/source/_static/css/custom_styling.css
Labels: Sphinx

#1016 Ending docstrings - iter 1
  verticapy/connection/connect.py
  verticapy/connection/external.py
  verticapy/connection/global_connection.py
  verticapy/connection/read.py
  verticapy/connection/utils.py
  verticapy/connection/write.py
  verticapy/core/parsers/all.py
  verticapy/core/parsers/avro.py
  verticapy/core/parsers/csv.py
  verticapy/core/parsers/json.py
  verticapy/core/parsers/pandas.py
  verticapy/core/parsers/shp.py
  verticapy/sql/geo/functions.py
  verticapy/sql/geo/index.py
Labels: Documentation

#1017 Update qprof.py
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
Labels: Performance

#1018 Multiple bug corrections
  verticapy/__init__.py
  verticapy/core/vdataframe/_aggregate.py
  verticapy/core/vdataframe/_read.py
  verticapy/core/vdataframe/base.py
  verticapy/jupyter/extensions/sql_magic.py
  verticapy/performance/vertica/qprof.py
Labels: Bug

#1019 Improving QPROF
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
Labels: Performance

#1020 Multiple corrections
  verticapy/__init__.py
  verticapy/connection/read.py
  verticapy/core/vdataframe/_plotting.py
  verticapy/performance/vertica/qprof.py
  verticapy/plotting/_plotly/base.py
  verticapy/plotting/_plotly/pie.py
  verticapy/plotting/base.py
Labels: Performance

#1021 QPROF Improvement
  verticapy/__init__.py
  verticapy/errors/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/plotting/_plotly/__init__.py
  verticapy/plotting/_plotly/subplots.py
  verticapy/plotting/base.py
Labels: Performance

#1022 QPROF Improvements
  verticapy/core/vdataframe/_plotting.py
  verticapy/performance/vertica/qprof.py
  verticapy/plotting/base.py
Labels: Plotting - Plotly, Plotting - Matplotlib, Plotting - Highcharts, Plotting - Base, Performance

#1023 QPROF improvement
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/plotting/_plotly/subplots.py
  verticapy/plotting/base.py
Labels: Plotting - Plotly, Plotting - Base, Performance

#1024 Adding tree file to qprof
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1025 QPROF bug correction
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
Labels: Performance

#1026 QPROF Improvements
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
  verticapy/plotting/_plotly/base.py
  verticapy/plotting/base.py
Labels: Performance

#1027 Create _inspect_statistics.py
  verticapy/__init__.py
  verticapy/_utils/_inspect_statistics.py
Labels: Documentation, GitHub - Description | CI.CD | Action

#1028 QPROF - Tree Correction
  verticapy/__init__.py
  verticapy/_utils/_inspect_statistics.py
  verticapy/core/vdataframe/_plotting.py
  verticapy/performance/vertica/tree.py
  verticapy/plotting/_plotly/subplots.py
Labels: Performance

#1031 QPROF Tree Correction + misc
  verticapy/__init__.py
  verticapy/_utils/_inspect_statistics.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1033 QPROF Improvements
  verticapy/__init__.py
  verticapy/core/vdataframe/_plotting.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
  verticapy/plotting/_plotly/bar.py
  verticapy/plotting/_plotly/barh.py
  verticapy/plotting/_plotly/subplots.py
Labels: Performance

#1034 QPROF Tree Improvement + misc
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
  verticapy/plotting/_plotly/subplots.py
Labels: Performance

#1035 QPROF - Trees
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1036 Generating codecov chart
  verticapy/__init__.py
  verticapy/_utils/_inspect_statistics.py
Labels: Config | Utils

#1032 778 tests vdataframe machine learning + join union sort + pivot
  verticapy/tests_new/core/vdataframe/test_join_union_sort.py
  verticapy/tests_new/core/vdataframe/test_machine_learning.py
  verticapy/tests_new/core/vdataframe/test_pivot.py
Labels: Unit Testing, Core - vDataFrame

#1037 QPROF - Tree
  verticapy/__init__.py
  verticapy/_utils/_inspect_statistics.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1039 Query Profiler - create_table correction.
  verticapy/__init__.py
  verticapy/_utils/_inspect_statistics.py
  verticapy/performance/vertica/qprof.py
Labels: Bug, Performance

#1040 QPROF - Bug correction
  verticapy/__init__.py
  verticapy/performance/vertica/tree.py
Labels: Bug

#1041 QPROF Tree Bug
  verticapy/__init__.py
  verticapy/core/tablesample/base.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Bug, Performance

#1044 Correcting Tree Bugs
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Bug, Performance

#1046 Sphinx - Fixed doc string bugs
  verticapy/core/tablesample/base.py
  verticapy/datasets/generators.py
  verticapy/machine_learning/memmodel/linear_model.py
  verticapy/machine_learning/model_selection/hp_tuning/plotting.py
Labels: Documentation

#1045 Sphinx New Pages RST
  docs/source/_static/benchmark_arima.csv
  docs/source/_static/benchmark_logr_table.csv
  docs/source/_static/benchmark_lr_table.csv
  docs/source/_static/benchmark_xgboost.csv
  docs/source/_static/benchmark_xgboost_100m.csv
  docs/source/_static/benchmark_xgboost_1b.csv
  docs/source/_static/benchmark_xgboost_amazon_custom.csv
  docs/source/_static/benchmark_xgboost_amazon_default.csv
  docs/source/_static/benchmark_xgboost_exp_custom.csv
  docs/source/_static/benchmark_xgboost_exp_default.csv
  docs/source/_static/css/custom_styling.css
  docs/source/_static/img_code_coverage_1.PNG
  docs/source/_static/img_code_coverage_2.PNG
  docs/source/_static/img_code_coverage_3.PNG
  docs/source/_static/img_udf_1.png
  docs/source/_static/img_udf_10.png
  docs/source/_static/img_udf_11.png
  docs/source/_static/img_udf_12.png
  docs/source/_static/img_udf_2.png
  docs/source/_static/img_udf_3.png
  docs/source/_static/img_udf_4.png
  docs/source/_static/img_udf_5.png
  docs/source/_static/img_udf_6.png
  docs/source/_static/img_udf_7.png
  docs/source/_static/img_udf_8.png
  docs/source/_static/img_udf_9.png
  docs/source/benchmarks.rst
  docs/source/benchmarks_arima.rst
  docs/source/benchmarks_linear_reg.rst
  docs/source/benchmarks_logistic_reg.rst
  docs/source/benchmarks_naive.rst
  docs/source/benchmarks_random_forest.rst
  docs/source/benchmarks_xgboost.rst
  docs/source/cicd.rst
  docs/source/cicd_black.rst
  docs/source/cicd_codecov.rst
  docs/source/cicd_pylint.rst
  docs/source/cicd_sphinx.rst
  docs/source/cicd_unittest.rst
  docs/source/connection.rst
  docs/source/connectors.rst
  docs/source/contribution_guidelines.rst
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/statistics.rst
  docs/source/user_defined_funcs.rst
Labels: Documentation

#1042 deleted old unit test that are part of new unit tests
  contributing/README.md
  verticapy/tests/vDataFrame/test_vDF_combine_join_sort.py
  verticapy/tests/vDataFrame/test_vDF_correlation.py
  verticapy/tests/vDataFrame/test_vDF_feature_engineering.py
  verticapy/tests/vDataFrame/test_vDF_preprocessing.py
Labels: Unit Testing

#1047 [Sphinx] Correction
  verticapy/__init__.py
  verticapy/_utils/_inspect_statistics.py
  verticapy/performance/vertica/tree.py
Labels: Bug

#1048 Sphinx - Corrections for Ensuring Complete Doc Compilation
  docs/source/_static/api_performance.svg
  docs/source/_static/cicd.png
  docs/source/_static/css/custom_styling.css
  docs/source/api.rst
  docs/source/benchmarks_arima.rst
  docs/source/benchmarks_linear_reg.rst
  docs/source/benchmarks_logistic_reg.rst
  docs/source/benchmarks_naive.rst
  docs/source/benchmarks_random_forest.rst
  docs/source/benchmarks_xgboost.rst
  docs/source/chart_gallery_boxplot.rst
  docs/source/chart_gallery_candlestick.rst
  docs/source/chart_gallery_geo.rst
  docs/source/chart_gallery_range.rst
  docs/source/chart_gallery_time_series.rst
  docs/source/conf.py
  docs/source/connect.rst
  docs/source/connection.rst
  docs/source/index.rst
  docs/source/machine_learning.rst
  docs/source/performance.rst
  docs/source/performance_vertica.rst
  docs/source/sql.rst
  docs/source/statistics.rst
  docs/source/utilities.rst
  verticapy/_config/config.py
  verticapy/core/parsers/all.py
  verticapy/core/parsers/avro.py
  verticapy/core/parsers/csv.py
  verticapy/core/tablesample/base.py
  verticapy/core/vdataframe/_plotting.py
  verticapy/core/vdataframe/_read.py
  verticapy/datasets/generators.py
  verticapy/jupyter/extensions/sql_magic.py
  verticapy/machine_learning/model_selection/kmeans.py
  verticapy/performance/vertica/qprof.py
  verticapy/sql/geo/index.py
Labels: Documentation

#1049 Tfidf unit test
  verticapy/tests_new/machine_learning/vertica/__init__.py
  verticapy/tests_new/machine_learning/vertica/test_tfidf.py
Labels: Unit Testing, Machine Learning - Text Analytics

#1051 New RST improvement
  docs/requirements.txt
  docs/source/conf.py
  verticapy/_utils/_display.py
  verticapy/core/vdataframe/_machine_learning.py
  verticapy/machine_learning/memmodel/cluster.py
  verticapy/machine_learning/memmodel/ensemble.py
  verticapy/machine_learning/memmodel/tree.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/performance/vertica/qprof.py
Labels: Enhancement, Sphinx

#1052 RST Corrections.
  docs/source/_static/css/custom_styling.css
  docs/source/conf.py
  docs/source/header_redirection/api/api.html
  docs/source/header_redirection/api/examples.html
  docs/source/header_redirection/api/home.html
  docs/source/header_redirection/api/index.html
  docs/source/header_redirection/api/user_guide.html
  docs/source/header_redirection/examples.html
  docs/source/header_redirection/home.html
  docs/source/statistics.rst
  verticapy/core/parsers/all.py
  verticapy/core/vdataframe/_machine_learning.py
  verticapy/machine_learning/memmodel/cluster.py
  verticapy/machine_learning/memmodel/ensemble.py
  verticapy/machine_learning/memmodel/tree.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/performance/vertica/qprof.py
Labels: Performance

#1053 Correcting the what's new file.
  docs/source/whats_new_v1_0_0.rst
Labels: Sphinx

#1057 Sphinx Docstring - Fixed some docstrings
  docs/source/machine_learning_vertica_clustering.rst
  docs/source/performance.rst
  docs/source/performance_vertica.rst
  verticapy/machine_learning/vertica/cluster.py
Labels: Documentation

#1058 [Sphinx] RST Changes
  docs/source/_static/css/custom_styling.css
  docs/source/api.rst
  docs/source/chart_gallery.rst
  docs/source/cicd_black.rst
  docs/source/connectors.rst
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/machine_learning_vertica_classification.rst
  docs/source/machine_learning_vertica_clustering.rst
  docs/source/machine_learning_vertica_decomposition.rst
  docs/source/machine_learning_vertica_text.rst
  docs/source/machine_learning_vertica_time_series.rst
  docs/source/performance.rst
  docs/source/tablesample.rst
  docs/source/user_guide_data_exploration.rst
  docs/source/user_guide_data_preparation.rst
  docs/source/user_guide_introduction.rst
  docs/source/user_guide_machine_learning.rst
  docs/source/utilities.rst
  docs/source/whats_new_v1_0_0.rst
  verticapy/core/tablesample/base.py
  verticapy/machine_learning/vertica/preprocessing.py
Labels: Sphinx

#1060 [QPROF] Improvement - Metrics
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1064 Qprof integration v2 00
  verticapy/__init__.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1065 [QPROF] Multiple metrics.
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1066 [QPROF] Supporting more elements
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1068 [QPROF] 2 LEGENDS + PROJ + BUG
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1070 Qprof integration v2 03
  verticapy/__init__.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1072 VerticaPy Themes
  verticapy/__init__.py
  verticapy/_config/config.py
  verticapy/_utils/_display.py
  verticapy/plotting/_plotly/bar.py
  verticapy/plotting/_plotly/base.py
Labels: Config | Utils

#1075 Qprof integration v2 04
  verticapy/__init__.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1076 [QPROF] Improving networking experience.
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1079 Update tree.py
  verticapy/__init__.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1081 Sphinx - Docstring - Small Fix
  verticapy/performance/vertica/qprof.py
Labels: Documentation

#1082 [Sphinx] Finalising the second iteration
  docs/source/_static/css/custom_styling.css
  docs/source/whats_new.rst
  docs/source/whats_new_v1_0_0.rst
  docs/source/whats_new_v1_0_1.rst
  verticapy/__init__.py
  verticapy/_config/config.py
  verticapy/_utils/_display.py
  verticapy/core/parsers/all.py
  verticapy/core/parsers/csv.py
  verticapy/core/parsers/json.py
  verticapy/core/parsers/pandas.py
  verticapy/core/tablesample/base.py
  verticapy/core/vdataframe/_aggregate.py
  verticapy/core/vdataframe/_corr.py
  verticapy/core/vdataframe/_encoding.py
  verticapy/core/vdataframe/_eval.py
  verticapy/core/vdataframe/_fill.py
  verticapy/core/vdataframe/_filter.py
  verticapy/core/vdataframe/_io.py
  verticapy/core/vdataframe/_join_union_sort.py
  verticapy/core/vdataframe/_machine_learning.py
  verticapy/core/vdataframe/_math.py
  verticapy/core/vdataframe/_pivot.py
  verticapy/core/vdataframe/_plotting.py
  verticapy/core/vdataframe/_plotting_animated.py
  verticapy/core/vdataframe/_read.py
  verticapy/core/vdataframe/_rolling.py
  verticapy/core/vdataframe/_scaler.py
  verticapy/core/vdataframe/_sys.py
  verticapy/core/vdataframe/_text.py
  verticapy/core/vdataframe/_typing.py
  verticapy/core/vdataframe/base.py
  verticapy/machine_learning/memmodel/tree.py
  verticapy/machine_learning/metrics/classification.py
  verticapy/machine_learning/metrics/regression.py
  verticapy/machine_learning/model_selection/hp_tuning/plotting.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/feature_extraction/text.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/naive_bayes.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/preprocessing.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/performance/vertica/qprof.py
  verticapy/sql/functions/analytic.py
  verticapy/sql/functions/conditional.py
  verticapy/sql/functions/date.py
  verticapy/sql/functions/math.py
  verticapy/sql/functions/null_handling.py
  verticapy/sql/functions/random.py
  verticapy/sql/functions/regexp.py
  verticapy/sql/functions/string.py
Labels: Sphinx

#1083 [SPHINX + QPROF] Bugs + allowing multiple transactions
  docs/source/benchmarks.rst
  docs/source/benchmarks_arima.rst
  docs/source/connection.rst
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/whats_new_v1_0_0.rst
  verticapy/__init__.py
  verticapy/core/parsers/all.py
  verticapy/core/parsers/csv.py
  verticapy/core/parsers/json.py
  verticapy/core/parsers/pandas.py
  verticapy/core/tablesample/base.py
  verticapy/core/vdataframe/_aggregate.py
  verticapy/core/vdataframe/_corr.py
  verticapy/core/vdataframe/_encoding.py
  verticapy/core/vdataframe/_eval.py
  verticapy/core/vdataframe/_fill.py
  verticapy/core/vdataframe/_filter.py
  verticapy/core/vdataframe/_io.py
  verticapy/core/vdataframe/_join_union_sort.py
  verticapy/core/vdataframe/_machine_learning.py
  verticapy/core/vdataframe/_math.py
  verticapy/core/vdataframe/_pivot.py
  verticapy/core/vdataframe/_plotting.py
  verticapy/core/vdataframe/_plotting_animated.py
  verticapy/core/vdataframe/_read.py
  verticapy/core/vdataframe/_rolling.py
  verticapy/core/vdataframe/_scaler.py
  verticapy/core/vdataframe/_sys.py
  verticapy/core/vdataframe/_text.py
  verticapy/core/vdataframe/_typing.py
  verticapy/core/vdataframe/base.py
  verticapy/machine_learning/memmodel/tree.py
  verticapy/machine_learning/metrics/classification.py
  verticapy/machine_learning/metrics/regression.py
  verticapy/machine_learning/model_selection/hp_tuning/plotting.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/feature_extraction/text.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/naive_bayes.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/preprocessing.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/performance/vertica/qprof.py
  verticapy/sql/functions/analytic.py
  verticapy/sql/functions/conditional.py
  verticapy/sql/functions/date.py
  verticapy/sql/functions/math.py
  verticapy/sql/functions/null_handling.py
  verticapy/sql/functions/random.py
  verticapy/sql/functions/regexp.py
  verticapy/sql/functions/string.py
Labels: Performance

#1085 Sphinx RST Pages - Updated Benchmarks
  docs/source/benchmarks_arima.rst
  docs/source/benchmarks_linear_reg.rst
  docs/source/benchmarks_logistic_reg.rst
  docs/source/benchmarks_naive.rst
  docs/source/benchmarks_random_forest.rst
  docs/source/benchmarks_xgboost.rst
Labels: Documentation

#1086 [Plotting + Sphinx] DARK/LIGHT/SPHINX
  docs/source/_static/css/custom_styling.css
  setup.py
  verticapy/__init__.py
  verticapy/_utils/_display.py
  verticapy/plotting/_highcharts/bar.py
  verticapy/plotting/_highcharts/base.py
  verticapy/plotting/_matplotlib/base.py
  verticapy/plotting/_plotly/base.py
Labels: Plotting - Plotly, Plotting - Matplotlib, Plotting - Highcharts, Plotting - Base

#1087 [QPROF] Key ID
  verticapy/_utils/_display.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1088 [QPROF] Improving the object
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Performance

#1089 Sphinx Script For Creating "On This Page" Toc Tree
  docs/create_toc_tree.py
  docs/source/benchmarks_xgboost.rst
Labels: Documentation, Sphinx

#1092 [SPHINX + PLOTTING + QPROF] Misc
  docs/create_toc_tree.py
  docs/source/_static/css/custom_styling.css
  docs/source/chart_gallery_tree.rst
  docs/source/cicd_codecov.rst
  requirements-dev.txt
  requirements-testing.txt
  verticapy/__init__.py
  verticapy/machine_learning/memmodel/cluster.py
  verticapy/machine_learning/memmodel/tree.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
  verticapy/plotting/_plotly/bar.py
  verticapy/plotting/base.py
  verticapy/tests/vModel/test_bisecting_kmeans.py
  verticapy/tests/vModel/test_dummy_tree_classifier.py
  verticapy/tests/vModel/test_dummy_tree_regressor.py
  verticapy/tests/vModel/test_iforest.py
  verticapy/tests/vModel/test_xgb_classifier.py
  verticapy/tests_new/machine_learning/vertica/test_tree_model.py
Labels: Jupyter, Website, Performance, Sphinx

#1094 [QPROF] Navigation
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
Labels: Performance

#1095 [QPROF] Bug correction
  verticapy/__init__.py
  verticapy/core/vdataframe/_read.py
  verticapy/performance/vertica/qprof.py
Labels: Performance

#1096 [QPROF] Warnings - tables
  verticapy/__init__.py
  verticapy/_utils/_sql/_collect.py
  verticapy/performance/vertica/qprof.py
Labels: Performance
