Repository vertica/VerticaPy, pull requests merged in 2023-11, with the labels that each got.

#799 PoissonRegressor
  verticapy/_utils/_sql/_vertica_version.py
  verticapy/machine_learning/vertica/__init__.py
  verticapy/machine_learning/vertica/linear_model.py
Labels: New Feature, Machine Learning - Regression

#798 Update _math.py
  verticapy/core/vdataframe/_math.py
  verticapy/tests/vDataFrame/test_vDF_feature_engineering.py
Labels: Bug

#803 UT for average_precision_score
  verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
Labels: Unit Testing, Machine Learning - Classification

#804 Making the "filter" method more consistent.
  verticapy/core/vdataframe/_filter.py
Labels: Enhancement

#806 Sphinx core vdataframe plotting vdf + vdc
  verticapy/core/vdataframe/_plotting.py
Labels: Documentation

#797 Correcting linear models hierarchy
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py
Labels: Bug

#809 Sphinx Docstring - SeeAlso for all plotting
  verticapy/core/vdataframe/_plotting.py
Labels: Documentation

#802 Sphinx Docstring Metrics for Classification
  verticapy/machine_learning/metrics/__init__.py
  verticapy/machine_learning/metrics/classification.py
Labels: Documentation

#813 Correcting AutoML bug
  verticapy/machine_learning/vertica/automl/supervised.py
Labels: Machine Learning - AutoML

#817 Supporting int for BinaryTreeRegressor
  verticapy/machine_learning/memmodel/tree.py
Labels: Bug

#818 Improving classification report
  verticapy/machine_learning/metrics/classification.py
Labels: Enhancement, Machine Learning - Classification

#822 PoissonRegressor UT
  verticapy/tests_new/machine_learning/vertica/__init__.py
  verticapy/tests_new/machine_learning/vertica/conftest.py
  verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py
  verticapy/tests_new/machine_learning/vertica/test_linear_model.py
Labels: Unit Testing, Machine Learning - Regression

#821 Adding parameters to to_db function
  verticapy/core/vdataframe/_io.py
  verticapy/core/vdataframe/_sys.py
Labels: Enhancement

#824 Sphinx Docstring - Fixed Classification Metrics
  verticapy/machine_learning/metrics/__init__.py
  verticapy/machine_learning/metrics/classification.py
Labels: Documentation

#819 docstring changes for memmodel/ensemble
  verticapy/machine_learning/memmodel/ensemble.py
  verticapy/machine_learning/memmodel/tree.py
Labels: Documentation

#828 sphinx docstring - update classification and regression metrics
  verticapy/machine_learning/metrics/classification.py
  verticapy/machine_learning/metrics/regression.py
Labels: Documentation

#826 uncommented math issue and increase tolerance for classification_metrics
  verticapy/tests_new/core/vdataframe/test_math.py
  verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
Labels: Unit Testing, Machine Learning - Classification, Core - vDataFrame

#829 Sphinx Docstring - model selection - basic examples
  verticapy/machine_learning/model_selection/statistical_tests/norm.py
  verticapy/machine_learning/model_selection/statistical_tests/ols.py
  verticapy/machine_learning/model_selection/statistical_tests/tsa.py
Labels: Documentation

#830 Adding TIME SERIES models (AR, MA, ARMA, ARIMA)
  verticapy/_utils/_sql/_vertica_version.py
  verticapy/machine_learning/vertica/__init__.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/model_management.py
  verticapy/machine_learning/vertica/tsa.py
  verticapy/plotting/_highcharts/__init__.py
  verticapy/plotting/_highcharts/machine_learning/tsa.py
  verticapy/plotting/_highcharts/range.py
  verticapy/plotting/_matplotlib/__init__.py
  verticapy/plotting/_matplotlib/machine_learning/tsa.py
  verticapy/plotting/_plotly/__init__.py
  verticapy/plotting/_plotly/line.py
  verticapy/plotting/_plotly/machine_learning/tsa.py
  verticapy/plotting/base.py
  verticapy/tests_new/machine_learning/vertica/test_linear_model.py
  verticapy/tests_new/machine_learning/vertica/test_tree_model.py
Labels: New Feature, Machine Learning - Time Series

#827 Add explode array function
  verticapy/_utils/_gen.py
  verticapy/core/vdataframe/_pivot.py
Labels: New Feature, Core - vDataFrame

#834 Model IMPORT/EXPORT + PMML Support
  verticapy/_utils/_sql/_vertica_version.py
  verticapy/machine_learning/vertica/__init__.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/model_management.py
  verticapy/machine_learning/vertica/pmml.py
Labels: Machine Learning - IO

#836 Version correction TS
  verticapy/_utils/_sql/_vertica_version.py
Labels: Machine Learning - Time Series

#839 Sphinx Docstring - Machine Learning / Vertica / TSA - Time series
  verticapy/machine_learning/vertica/tsa.py
Labels: Documentation

#843 autoregressor unit test code
  verticapy/tests_new/conftest.py
  verticapy/tests_new/machine_learning/vertica/__init__.py
  verticapy/tests_new/machine_learning/vertica/conftest.py
  verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py
  verticapy/tests_new/machine_learning/vertica/test_linear_model.py
  verticapy/tests_new/machine_learning/vertica/test_tree_model.py
Labels: Unit Testing, Machine Learning - Time Series

#844 Correcting indexes
  verticapy/machine_learning/vertica/tsa.py
Labels: Bug, Machine Learning - Time Series

#849 832 AR, MA, ARMA, ARIMA unit test
  verticapy/tests_new/machine_learning/vertica/__init__.py
  verticapy/tests_new/machine_learning/vertica/conftest.py
  verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py
  verticapy/tests_new/machine_learning/vertica/test_linear_model.py
Labels: Unit Testing, Machine Learning - Time Series

#846 sphinx docstring changes for vdataframe/typing
  verticapy/core/vdataframe/_typing.py
Labels: Documentation

#848 Time Series improvement
  verticapy/machine_learning/vertica/tsa.py
  verticapy/plotting/_highcharts/machine_learning/tsa.py
  verticapy/plotting/_matplotlib/machine_learning/tsa.py
  verticapy/plotting/_plotly/machine_learning/tsa.py
  verticapy/plotting/base.py
Labels: Machine Learning - Time Series

#853 Docstring Update for TSA
  docs/reverse_replace_sphinx_dir.py
  verticapy/machine_learning/vertica/tsa.py
Labels: Documentation

#842 Tf-idf
  verticapy/machine_learning/vertica/feature_extraction/__init__.py
  verticapy/machine_learning/vertica/feature_extraction/text.py
Labels: New Feature, Text Analytics

#858 Ignoring old MATPLOTLIB tests
  setup.py
  verticapy/tests/vDataFrame/test_vDF_plot.py
  verticapy/tests/vModel/test_bisecting_kmeans.py
  verticapy/tests/vModel/test_dbscan.py
  verticapy/tests/vModel/test_decision_tree_classifier.py
  verticapy/tests/vModel/test_decision_tree_regressor.py
  verticapy/tests/vModel/test_dummy_tree_classifier.py
  verticapy/tests/vModel/test_dummy_tree_regressor.py
  verticapy/tests/vModel/test_elastic_net.py
  verticapy/tests/vModel/test_iforest.py
  verticapy/tests/vModel/test_kde.py
  verticapy/tests/vModel/test_kmeans.py
  verticapy/tests/vModel/test_knn_classifier.py
  verticapy/tests/vModel/test_knn_regressor.py
  verticapy/tests/vModel/test_kprototypes.py
  verticapy/tests/vModel/test_lasso.py
  verticapy/tests/vModel/test_linear_regression.py
  verticapy/tests/vModel/test_linear_svc.py
  verticapy/tests/vModel/test_linear_svr.py
  verticapy/tests/vModel/test_lof.py
  verticapy/tests/vModel/test_logistic_regression.py
  verticapy/tests/vModel/test_mca.py
  verticapy/tests/vModel/test_naive_bayes.py
  verticapy/tests/vModel/test_nearestcentroid.py
  verticapy/tests/vModel/test_pca.py
  verticapy/tests/vModel/test_randomforest_classifier.py
  verticapy/tests/vModel/test_randomforest_regressor.py
  verticapy/tests/vModel/test_ridge.py
  verticapy/tests/vModel/test_svd.py
  verticapy/tests/vModel/test_xgb_classifier.py
  verticapy/tests/vModel/test_xgb_regressor.py
Labels: Config | Utils

#861 Sphinx - model selection / statistical tests - 2
  verticapy/machine_learning/model_selection/statistical_tests/norm.py
Labels: Documentation

#864 Improve TF-IDF
  verticapy/machine_learning/vertica/feature_extraction/text.py
Labels: Text Analytics

#865 Sphinx Docstring for OLS functions
  verticapy/machine_learning/model_selection/statistical_tests/ols.py
Labels: Documentation

#868 TF IDF - Improvement 2
  verticapy/machine_learning/vertica/feature_extraction/text.py
Labels: Text Analytics

#869 Correcting Statistical Tests
  verticapy/core/vdataframe/_corr.py
  verticapy/machine_learning/model_selection/statistical_tests/tsa.py
  verticapy/tests/vDataFrame/test_vDF_descriptive_statistics.py
  verticapy/tests/vDataFrame/test_vDF_plot_plotly.py
  verticapy/tests_new/machine_learning/vertica/conftest.py
  verticapy/tests_new/mlops/test_model_tracking.py
  verticapy/tests_new/mlops/test_model_versioning.py
  verticapy/tests_new/plotting/base_test_files.py
Labels: Bug, Machine Learning - Statistical Tests

#871 Sphinx Docstring - Added docstring for all OLS + adfuller
  verticapy/machine_learning/model_selection/statistical_tests/ols.py
  verticapy/machine_learning/model_selection/statistical_tests/tsa.py
Labels: Documentation

#872 Making TS Plots and FI consistent
  verticapy/machine_learning/vertica/tsa.py
  verticapy/plotting/_highcharts/machine_learning/tsa.py
  verticapy/plotting/_matplotlib/machine_learning/tsa.py
  verticapy/plotting/_plotly/machine_learning/tsa.py
Labels: Machine Learning - Time Series

#873 Norm the API
  docs/source/stats.rst
  verticapy/core/vdataframe/_corr.py
  verticapy/core/vdataframe/_encoding.py
  verticapy/machine_learning/model_selection/hp_tuning/cv.py
  verticapy/machine_learning/model_selection/kmeans.py
  verticapy/machine_learning/model_selection/model_validation.py
  verticapy/machine_learning/model_selection/statistical_tests/__init__.py
  verticapy/machine_learning/model_selection/statistical_tests/ols.py
  verticapy/machine_learning/model_selection/statistical_tests/tsa.py
  verticapy/machine_learning/model_selection/variables_selection.py
  verticapy/machine_learning/vertica/automl/clustering.py
  verticapy/machine_learning/vertica/automl/dataprep.py
  verticapy/machine_learning/vertica/automl/supervised.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/feature_extraction/text.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/pipeline.py
  verticapy/machine_learning/vertica/preprocessing.py
  verticapy/stats/__init__.py
  verticapy/tests/stats/test_stats.py
Labels: Enhancement

#874 Sphinx Docstring - model selection / statistical tests / tsa
  docs/source/stats.rst
  verticapy/machine_learning/model_selection/statistical_tests/tsa.py
Labels: Documentation

#876 Query Profile v0
  verticapy/performance/__init__.py
  verticapy/performance/vertica/__init__.py
  verticapy/performance/vertica/qprof.py
Labels: Enhancement

#877 Multiple corrections - Formatter + temp_schema
  verticapy/_utils/_sql/_display.py
  verticapy/_utils/_sql/_format.py
  verticapy/core/parsers/all.py
  verticapy/core/parsers/csv.py
  verticapy/core/parsers/json.py
  verticapy/core/parsers/shp.py
  verticapy/core/vdataframe/_encoding.py
  verticapy/core/vdataframe/_sys.py
  verticapy/datasets/loaders.py
  verticapy/datasets/tests_loaders.py
  verticapy/machine_learning/vertica/base.py
  verticapy/sql/drop.py
  verticapy/sql/dtypes.py
  verticapy/sql/insert.py
Labels: Enhancement

#878 Quick Fix - remove unnecessary print
  verticapy/plotting/_plotly/line.py
Labels: Bug, Plotting - Plotly

#882 qprof_adding_query_support
  verticapy/performance/vertica/qprof.py
  verticapy/plotting/base.py
Labels: Enhancement

#881 Sphinx Docstring - machine_learning / vertica / neighbors
  verticapy/machine_learning/vertica/neighbors.py
Labels: Documentation

#880 Sphinx Docstring model selection / variable selection
  verticapy/_config/config.py
  verticapy/core/vdataframe/_aggregate.py
  verticapy/core/vdataframe/_corr.py
  verticapy/core/vdataframe/_encoding.py
  verticapy/core/vdataframe/_plotting.py
  verticapy/core/vdataframe/_text.py
  verticapy/core/vdataframe/_typing.py
  verticapy/datasets/generators.py
  verticapy/datasets/loaders.py
  verticapy/jupyter/extensions/chart_magic.py
  verticapy/jupyter/extensions/sql_magic.py
  verticapy/machine_learning/model_selection/statistical_tests/norm.py
  verticapy/machine_learning/model_selection/statistical_tests/ols.py
  verticapy/machine_learning/model_selection/statistical_tests/tsa.py
  verticapy/machine_learning/model_selection/variables_selection.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/decomposition.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/naive_bayes.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/machine_learning/vertica/tsa.py
  verticapy/sql/create.py
  verticapy/sql/functions/analytic.py
  verticapy/sql/functions/conditional.py
  verticapy/sql/functions/date.py
  verticapy/sql/functions/math.py
  verticapy/sql/functions/null_handling.py
  verticapy/sql/functions/random.py
  verticapy/sql/functions/regexp.py
  verticapy/sql/functions/string.py
  verticapy/sql/geo/functions.py
  verticapy/sql/geo/index.py
Labels: Documentation

#884 Sphinx Docstring Update + bugfix for TFIDF
  verticapy/machine_learning/vertica/feature_extraction/text.py
Labels: Bug, Documentation

#886 small corrections
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/model_management.py
Labels: Bug

#885 QPROF + Query Formatting
  verticapy/_utils/_sql/_format.py
  verticapy/performance/vertica/qprof.py
  verticapy/plotting/base.py
Labels: Enhancement, Performance

#889 Improving QPROF
  verticapy/performance/vertica/qprof.py
  verticapy/plotting/base.py
Labels: Performance

#891 Sphinx rst files
  docs/source/_static/css/custom_styling.css
  docs/source/conf.py
  docs/source/user_guide.rst
  docs/source/user_guide_data_exploration.rst
  docs/source/user_guide_data_preparation.rst
  docs/source/user_guide_full_stack.rst
  docs/source/user_guide_introduction.rst
  docs/source/user_guide_machine_learning.rst
Labels: Documentation

#893 Sphinx Docstring - core/vdataframe/animated_plots
  verticapy/core/vdataframe/_plotting_animated.py
Labels: Documentation

#892 QPROF Improvements
  verticapy/_utils/_sql/_format.py
  verticapy/performance/vertica/qprof.py
Labels: Performance

#894 QPROF + DOCSTRINGS
  verticapy/_utils/_sql/_format.py
  verticapy/core/vdataframe/_plotting_animated.py
  verticapy/core/vdataframe/_utils.py
  verticapy/machine_learning/memmodel/ensemble.py
  verticapy/machine_learning/memmodel/tree.py
  verticapy/performance/vertica/qprof.py
Labels: Performance

#898 Removing some old tests
  verticapy/tests/vDataFrame/test_vDF_correlation.py
  verticapy/tests/vDataFrame/test_vDF_descriptive_statistics.py
  verticapy/tests/vDataFrame/test_vDF_feature_engineering.py
  verticapy/tests/vModel/test_decision_tree_classifier.py
  verticapy/tests/vModel/test_decision_tree_regressor.py
  verticapy/tests/vModel/test_elastic_net.py
  verticapy/tests/vModel/test_lasso.py
  verticapy/tests/vModel/test_linear_regression.py
  verticapy/tests/vModel/test_randomforest_classifier.py
  verticapy/tests/vModel/test_randomforest_regressor.py
  verticapy/tests/vModel/test_ridge.py
  verticapy/tests/vModel/test_xgb_regressor.py
Labels: Unit Testing

#899 Sphinx Docstring Core / vdataframe / fill + filter
  verticapy/core/vdataframe/_fill.py
  verticapy/core/vdataframe/_filter.py
Labels: Documentation

#900 Sphinx RST File Modification - Added QueryProfiler
  docs/source/utilities.rst
  verticapy/core/vdataframe/_plotting_animated.py
  verticapy/core/vdataframe/_scaler.py
  verticapy/core/vdataframe/_text.py
  verticapy/core/vdataframe/_utils.py
  verticapy/machine_learning/memmodel/ensemble.py
  verticapy/machine_learning/memmodel/preprocessing.py
  verticapy/machine_learning/memmodel/tree.py
  verticapy/machine_learning/vertica/preprocessing.py
  verticapy/sql/functions/regexp.py
  verticapy/sql/geo/functions.py
  verticapy/sql/geo/index.py
Labels: Documentation

#901 Removing old plot tests
  verticapy/tests/vDataFrame/test_vDF_plot.py
  verticapy/tests/vDataFrame/test_vDF_plot_plotly.py
  verticapy/tests/vModel/test_delphi.py
  verticapy/tests_new/machine_learning/vertica/conftest.py
Labels: Unit Testing

#930 Sphinx doc visual modifications
  docs/source/_static/css/custom_styling.css
  docs/source/conf.py
  docs/source/connectors.rst
  docs/source/index.rst
  docs/source/machine_learning.rst
  docs/source/machine_learning_memmodels.rst
  docs/source/machine_learning_vertica.rst
  docs/source/user_guide.rst
Labels: Documentation, Sphinx

#931 Sphinx Docstring vdataframe/_sys
  docs/source/vdataframe.rst
  verticapy/core/vdataframe/_filter.py
  verticapy/core/vdataframe/_sys.py
  verticapy/core/vdataframe/_text.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/neighbors.py
Labels: Documentation

#933 Sphinx Docstring core / vdataframe / _math
  verticapy/core/vdataframe/_math.py
Labels: Documentation

#934 Sphinx Docstring core / vdataframe / _pivot
  verticapy/core/vdataframe/_pivot.py
Labels: Documentation

#938 Sphinx Docstring for core / vdataframe / _rolling functions
  verticapy/core/vdataframe/_rolling.py
Labels: Documentation

#943 Sphinx Docstring - Enhanced docstrings for JOIN
  verticapy/core/vdataframe/_join_union_sort.py
  verticapy/core/vdataframe/_sys.py
Labels: Documentation

#944 Sphinx Docstring - core / vdataframe / _read
  verticapy/core/vdataframe/_read.py
Labels: Documentation

#945 Multiple docstrings
  docs/source/error.rst
  verticapy/errors/__init__.py
  verticapy/sql/geo/functions.py
  verticapy/sql/geo/index.py
Labels: Documentation

#947 Multiple docstrings + correction
  docs/source/contribution_guidelines_code_auto_doc_example.rst
  docs/source/user_guide.rst
  docs/source/user_guide_introduction.rst
  docs/source/whats_new_v1_0_0.rst
  verticapy/_config/config.py
  verticapy/_config/validators.py
  verticapy/core/string_sql/base.py
  verticapy/core/vdataframe/_join_union_sort.py
  verticapy/core/vdataframe/_math.py
  verticapy/core/vdataframe/_pivot.py
  verticapy/core/vdataframe/_read.py
  verticapy/core/vdataframe/_rolling.py
  verticapy/core/vdataframe/_sys.py
  verticapy/core/vdataframe/_utils.py
  verticapy/core/vdataframe/base.py
  verticapy/sql/geo/functions.py
  verticapy/sql/geo/index.py
Labels: Documentation

#950 Sphinx Docstring core vdataframe / machine learning
  verticapy/core/vdataframe/_machine_learning.py
Labels: Documentation

#961 Multiple docstrings
  verticapy/_utils/_gen.py
  verticapy/_utils/_logo.py
  verticapy/_utils/_map.py
  verticapy/_utils/_object.py
  verticapy/_utils/_parsers.py
  verticapy/_utils/_sql/_check.py
  verticapy/_utils/_sql/_dblink.py
  verticapy/_utils/_sql/_display.py
  verticapy/_utils/_sql/_random.py
  verticapy/_utils/_sql/_vertica_version.py
  verticapy/core/vdataframe/_read.py
Labels: Documentation

#962 Sphinx docstring changes for vdataframe/io
  verticapy/core/vdataframe/_io.py
Labels: Documentation

#963 Format Misc - docstrings
  verticapy/core/string_sql/base.py
  verticapy/core/vdataframe/_encoding.py
  verticapy/core/vdataframe/_eval.py
  verticapy/core/vdataframe/_fill.py
  verticapy/core/vdataframe/_filter.py
  verticapy/core/vdataframe/_io.py
  verticapy/core/vdataframe/_join_union_sort.py
  verticapy/core/vdataframe/_machine_learning.py
  verticapy/core/vdataframe/_math.py
  verticapy/core/vdataframe/_pivot.py
  verticapy/core/vdataframe/_read.py
  verticapy/core/vdataframe/_rolling.py
  verticapy/core/vdataframe/_scaler.py
  verticapy/core/vdataframe/_sys.py
  verticapy/core/vdataframe/_typing.py
  verticapy/core/vdataframe/_utils.py
  verticapy/core/vdataframe/base.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/machine_learning/vertica/tsa.py
  verticapy/sdk/vertica/udf/gen.py
  verticapy/sdk/vertica/udf/load.py
  verticapy/sql/geo/functions.py
Labels: Documentation

#946 ARIMA accuracy unit test
  verticapy/tests_new/machine_learning/vertica/__init__.py
  verticapy/tests_new/machine_learning/vertica/conftest.py
  verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py
  verticapy/tests_new/machine_learning/vertica/test_linear_model.py
Labels: Unit Testing, Machine Learning - Time Series
