Repository vertica/VerticaPy, pull requests merged in 2023-10, with the labels that each got.

#734 ACF Plot - minor changes
  verticapy/plotting/_highcharts/acf.py
  verticapy/plotting/_plotly/acf.py
Labels: Bug, Plotting - Plotly, Plotting - Highcharts

#740 Validation Curve Plot - renaming return_chart to show
  verticapy/machine_learning/model_selection/hp_tuning/plotting.py
Labels: Plotting - Base

#736 UT code for encoding, fill and normalize
  verticapy/tests_new/conftest.py
  verticapy/tests_new/core/vdataframe/test_encoding.py
  verticapy/tests_new/core/vdataframe/test_fill.py
  verticapy/tests_new/core/vdataframe/test_normalize.py
Labels: Unit Testing, Core - vDataFrame

#743 Plotly voronoi colors
  verticapy/plotting/_plotly/machine_learning/kmeans.py
  verticapy/tests/vModel/test_iforest.py
Labels: Enhancement, Plotting - Plotly

#726 _config directory sphinx conversion
  verticapy/_config/config.py
Labels: Documentation

#733 sphinx conversion -- sdk module
  verticapy/sdk/vertica/udf/gen.py
  verticapy/sdk/vertica/udf/load.py
Labels: Documentation

#744 Sphinx - Aggregate - Updating Doc Strings
  verticapy/core/vdataframe/_aggregate.py
Labels: Documentation

#738 Plotly Outliers Plot - Added color customization option
  verticapy/plotting/_plotly/outliers.py
Labels: Bug, Plotting - Plotly

#732 sphinx conversion -- the rest of datasets directory
  verticapy/datasets/loaders.py
Labels: Documentation

#731 sphinx conversion connection directory
  verticapy/connection/connect.py
  verticapy/connection/external.py
  verticapy/connection/read.py
  verticapy/connection/utils.py
  verticapy/connection/write.py
Labels: Documentation

#737 sphinx conversion -- sql magic
  verticapy/jupyter/extensions/chart_magic.py
  verticapy/jupyter/extensions/sql_magic.py
Labels: Documentation

#745 UT for vDataFrame - typing and text
  verticapy/tests_new/conftest.py
  verticapy/tests_new/core/vdataframe/test_text.py
  verticapy/tests_new/core/vdataframe/test_typing.py
Labels: Unit Testing, Core - vDataFrame

#724 Sphinx conversion sql directory
  verticapy/sql/create.py
  verticapy/sql/drop.py
  verticapy/sql/dtypes.py
  verticapy/sql/flex.py
  verticapy/sql/functions/analytic.py
  verticapy/sql/functions/conditional.py
  verticapy/sql/functions/date.py
  verticapy/sql/functions/math.py
  verticapy/sql/functions/null_handling.py
  verticapy/sql/functions/random.py
  verticapy/sql/functions/regexp.py
  verticapy/sql/functions/string.py
  verticapy/sql/geo/functions.py
  verticapy/sql/geo/index.py
  verticapy/sql/insert.py
Labels: Documentation

#748 SPHINX - verticapy.core.vDataFrame._aggregate
  verticapy/core/vdataframe/_aggregate.py
  verticapy/tests/vDataFrame/test_vDF_descriptive_statistics.py
Labels: Documentation

#750 Enabling test learning curve
  .github/workflows/ci.yaml
  .github/workflows/master-codecov.yml
  verticapy/tests/vModel/test_model_selection.py
Labels: Enhancement, GitHub - Description | CI.CD | Action

#751 Finalising corr's docstring
  verticapy/core/vdataframe/_corr.py
Labels: Documentation

#753 Sphinx Docstring Update for MachineLearning/Vertica/LinearModel
  verticapy/machine_learning/vertica/linear_model.py
Labels: Documentation

#754 Some bug fixes for doc strings
  verticapy/_config/config.py
  verticapy/jupyter/extensions/chart_magic.py
  verticapy/sql/geo/index.py
  verticapy/sql/insert.py
Labels: Bug, Documentation

#758 Sphinx machine learning/vertica/linear model
  verticapy/machine_learning/vertica/linear_model.py
Labels: Documentation

#759 Sphinx Docstring Update for SVM + Tree
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
Labels: Documentation

#760 Sphinx docstring machine learning vertica
  verticapy/machine_learning/vertica/ensemble.py
Labels: Documentation

#762 Bugfix _ Isolation Forest Anomaly Plot
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/linear_model.py
Labels: Bug, Plotting - Base

#763 Docstring Fix - Added Contour Plot
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
Labels: Documentation

#761 Sphinx Docstring Update - XGB Regressor + Classifier
  verticapy/machine_learning/vertica/ensemble.py
Labels: Documentation

#765 Sphinx Docstring Update for Vertica Models - Include Graphviz
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
Labels: Documentation

#766 Sphinx Docstring Update - Bisecting KMeans
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/ensemble.py
Labels: Documentation

#770 Sphinx Docstring Update -ML/Vertica/KMeans + KPrototypes (Black Fix)
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/ensemble.py
Labels: Documentation

#772 sphinx docstring - ml/vertica/naive_bayes
  verticapy/machine_learning/vertica/naive_bayes.py
Labels: Documentation

#771 Sphinx Docstring ml/vertica/decomposition
  verticapy/machine_learning/memmodel/decomposition.py
  verticapy/machine_learning/vertica/decomposition.py
Labels: Documentation

#779 Bugfix - Matplotlib - Candlestick Plot
  verticapy/machine_learning/memmodel/naive_bayes.py
  verticapy/plotting/_matplotlib/candlestick.py
Labels: Bug, Plotting - Matplotlib

#782 Sphinx Docstring Update - Nearest Centroid
  verticapy/machine_learning/memmodel/cluster.py
  verticapy/machine_learning/metrics/classification.py
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/cluster.py
Labels: Bug, Documentation

#785 Correcting format_relation
  verticapy/_utils/_sql/_format.py
Labels: Bug, Config | Utils

#784 Update naive_bayes.py
  verticapy/machine_learning/vertica/naive_bayes.py
Labels: Bug, Machine Learning - Classification

#792 Sphinx Docstring - OneHotEncoder
  verticapy/machine_learning/vertica/preprocessing.py
Labels: Documentation

#791 docstring changes for memmodel/preprocessing
  verticapy/machine_learning/memmodel/preprocessing.py
Labels: Documentation

#788 Updating version and support
  .github/workflows/ci.yaml
  .github/workflows/master-codecov.yml
  setup.py
  tox.ini
  verticapy/__init__.py
  verticapy/core/vdataframe/_filter.py
  verticapy/core/vdataframe/_machine_learning.py
  verticapy/machine_learning/model_selection/model_validation.py
Labels: GitHub - Description | CI.CD | Action

#794 making clearer auc, prc
  verticapy/machine_learning/metrics/classification.py
Labels: Enhancement

#793 Improving the model summary - fit
  verticapy/machine_learning/vertica/base.py
Labels: Enhancement

#795 Sphinx Docstring for Preprocessing
  verticapy/machine_learning/vertica/preprocessing.py
Labels: Documentation

#801 Sphinx Docstring Regression Metrics
  verticapy/machine_learning/metrics/regression.py
Labels: Documentation
