Repository vertica/VerticaPy, pull requests merged in 2024-01, with the labels that each got.

#1100 Reshaping the template of the Issues tab
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue.yml
Labels: GitHub - Description | CI.CD | Action

#1097 [Data Preparation] Improving seasonal_decompose function
  README.md
  assets/cheat_sheet/VerticaPy Machine Learning Cheat Sheet.docx
  assets/cheat_sheet/VerticaPy Machine Learning Cheat Sheet.pdf
  assets/img/architecture.png
  assets/img/benefits.png
  assets/img/logo.png
  change_logs/change_log_v1.0.0-beta.md
  contributing/README.md
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/whats_new_v1_0_1.rst
  img/charts.gif
  img/check_types.png
  img/description.png
  img/examples.gif
  img/function.png
  img/vdf_file.png
  verticapy/__init__.py
  verticapy/machine_learning/model_selection/statistical_tests/tsa.py
  verticapy/performance/vertica/qprof.py
  verticapy/tests/stats/test_stats.py
Labels: Machine Learning - Time Series

#1101 [QPROF] Improving Warnings + BUG correction
  docs/source/performance_vertica.rst
  verticapy/_utils/_sql/_sys.py
  verticapy/core/tablesample/base.py
  verticapy/core/vdataframe/_read.py
  verticapy/core/vdataframe/base.py
  verticapy/performance/vertica/qprof.py
Labels: Performance

#1102 Sphinx plot transparency
  verticapy/core/vdataframe/_plotting.py
  verticapy/plotting/_plotly/heatmap.py
  verticapy/plotting/_plotly/machine_learning/svm.py
Labels: Enhancement

#1103 Bug Corrections
  README.md
  setup.py
  verticapy/core/vdataframe/_read.py
  verticapy/performance/vertica/qprof.py
Labels: Bug

#1104 Sphinx font size adjustment for Doc Website
  docs/source/_static/css/custom_styling.css
  docs/source/api.rst
  docs/source/benchmarks.rst
  docs/source/machine_learning.rst
  docs/source/machine_learning_memmodels.rst
  docs/source/machine_learning_vertica.rst
  docs/source/performance.rst
  docs/source/user_guide.rst
Labels: Documentation

#1108 Sphinx script - For shortening Next-Page and Prev-Page reference text
  docs/refresh.sh
  docs/remove_pattern.py
Labels: Documentation

#1110 Update readme - Added GIFs + Themes
  README.md
Labels: Documentation

#1115 Updated Cheat-sheet
  assets/cheat_sheet/VerticaPy Machine Learning Cheat Sheet.docx
  assets/cheat_sheet/VerticaPy Machine Learning Cheat Sheet.pdf
Labels: Documentation

#1114 Sphinx Compiling Corrections + Minor Bug
  docs/source/_static/css/custom_styling.css
  docs/source/chart_gallery_seasonal.rst
  verticapy/performance/vertica/qprof.py
Labels: Bug, Documentation

#1116 Update cheat sheet
  README.md
  assets/cheat_sheet/1.0.x/VerticaPy_Machine_Learning_Cheat_Sheet_1_0_1.docx
  assets/cheat_sheet/1.0.x/VerticaPy_Machine_Learning_Cheat_Sheet_1_0_1.pdf
Labels: Documentation

#1119 Sphinx font size increase + script update
  docs/remove_pattern.py
  docs/source/_static/css/custom_styling.css
  docs/source/index.rst
Labels: Documentation

#1120 Sphinx RST Update - Added Base Classes for Plotting Libraries in vDataFrame Page
  docs/source/vdataframe.rst
Labels: Documentation

#1122 Sphinx - Chart Gallery Page - Made GIFs Transparent
  docs/source/_static/css/custom_styling.css
  docs/source/_static/gif_acf.gif
  docs/source/_static/gif_animated.gif
  docs/source/_static/gif_area.gif
  docs/source/_static/gif_bar.gif
  docs/source/_static/gif_boxplot.gif
  docs/source/_static/gif_candlestick.gif
  docs/source/_static/gif_champion_challenger.gif
  docs/source/_static/gif_classification_curve.gif
  docs/source/_static/gif_classification_plot.gif
  docs/source/_static/gif_contour_plot.gif
  docs/source/_static/gif_corr.gif
  docs/source/_static/gif_density.gif
  docs/source/_static/gif_geo.gif
  docs/source/_static/gif_hist.gif
  docs/source/_static/gif_learning.gif
  docs/source/_static/gif_line.gif
  docs/source/_static/gif_lof.gif
  docs/source/_static/gif_outliers.gif
  docs/source/_static/gif_pie.gif
  docs/source/_static/gif_pivot.gif
  docs/source/_static/gif_range.gif
  docs/source/_static/gif_regression_plot.gif
  docs/source/_static/gif_scatter.gif
  docs/source/_static/gif_spider.gif
  docs/source/_static/gif_stepwise.gif
  docs/source/_static/gif_time_series.gif
  docs/source/_static/gif_tree.gif
  docs/source/_static/pic_champion_challenger.png
  docs/source/_static/pic_elbow.png
  docs/source/_static/pic_seasonal.PNG
  docs/source/_static/pic_time_series.png
  docs/source/_static/pic_tree.png
  docs/source/chart_gallery.rst
Labels: Website

#1111 added new UTs for eval,read and filter vDataframe and deleted old UTs
  verticapy/tests/vDataFrame/test_vDF_descriptive_statistics.py
  verticapy/tests/vDataFrame/test_vDF_filter_sample.py
  verticapy/tests/vDataFrame/test_vDF_preprocessing.py
  verticapy/tests/vDataFrame/test_vDF_utilities.py
  verticapy/tests_new/core/vdataframe/test_eval.py
  verticapy/tests_new/core/vdataframe/test_filter.py
  verticapy/tests_new/core/vdataframe/test_read.py
Labels: Unit Testing, Core - vDataFrame

#1126 Sphinx fix
  docs/notebook_correction.py
  docs/refresh.sh
  docs/source/_static/css/custom_styling.css
  docs/source/benchmarks_arima.rst
  docs/source/benchmarks_linear_reg.rst
  docs/source/benchmarks_logistic_reg.rst
  docs/source/benchmarks_naive.rst
  docs/source/benchmarks_random_forest.rst
  docs/source/benchmarks_xgboost.rst
  docs/source/user_guide_data_exploration.rst
  docs/source/user_guide_data_preparation.rst
  docs/source/user_guide_full_stack.rst
  docs/source/user_guide_machine_learning.rst
  docs/source/whats_new_v1_0_0.rst
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/cluster.py
  verticapy/machine_learning/vertica/decomposition.py
  verticapy/machine_learning/vertica/ensemble.py
  verticapy/machine_learning/vertica/linear_model.py
  verticapy/machine_learning/vertica/naive_bayes.py
  verticapy/machine_learning/vertica/neighbors.py
  verticapy/machine_learning/vertica/preprocessing.py
  verticapy/machine_learning/vertica/svm.py
  verticapy/machine_learning/vertica/tree.py
  verticapy/machine_learning/vertica/tsa.py
  verticapy/performance/vertica/qprof.py
Labels: Documentation, Website

#1127 Updating release number
  setup.py
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
Labels: Performance

#1129 Update Readme + What's New
  README.md
  docs/source/whats_new_v1_0_1.rst
Labels: Documentation

#1130 Sphinx - Fix post-processing of docs
  docs/fix_links.py
  docs/fix_logo.py
  docs/fix_search.py
  docs/notebook_correction.py
  docs/source/_static/css/custom_styling.css
  docs/source/_static/ot_favicon.svg
Labels: Documentation, Website

#1132 added tolerance for dict results
  verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
Labels: Unit Testing, Machine Learning - Classification

#1131 Plotly Scatter Plot - bugfix + Unit Test update
  verticapy/plotting/_plotly/scatter.py
  verticapy/tests_new/plotting/base_test_files.py
Labels: Bug, Unit Testing, Plotting - Plotly

#1136 added code to generate error report for lr and tree models
  verticapy/tests_new/machine_learning/vertica/test_linear_model.py
  verticapy/tests_new/machine_learning/vertica/test_tree_model.py
Labels: Unit Testing, Machine Learning - Regression
