Repository vertica/VerticaPy, pull requests merged in 2024-02, with the labels that each got.

#1146 adding unit tests for memmodel
  verticapy/tests_new/machine_learning/memmodel/test_cluster.py
  verticapy/tests_new/machine_learning/memmodel/test_decomposition.py
  verticapy/tests_new/machine_learning/memmodel/test_linear_model.py
  verticapy/tests_new/machine_learning/memmodel/test_naive_bayes.py
  verticapy/tests_new/machine_learning/memmodel/test_preprocessing.py
Labels: Unit Testing

#1150 Unit test for memmodel.tree and memmodel.ensemble
  verticapy/tests_new/machine_learning/memmodel/test_cluster.py
  verticapy/tests_new/machine_learning/memmodel/test_ensemble.py
  verticapy/tests_new/machine_learning/memmodel/test_tree.py
Labels: Unit Testing

#1151 Added Plotly Plot for Scree and Var
  verticapy/plotting/_plotly/__init__.py
  verticapy/plotting/_plotly/machine_learning/pca.py
  verticapy/tests_new/plotting/base_test_files.py
  verticapy/tests_new/plotting/highcharts/machine_learning/test_highcharts_pca.py
  verticapy/tests_new/plotting/plotly/machine_learning/test_plotly_pca.py
Labels: Unit Testing, Plotting - Plotly

#1152 Correcting all QPROF bug
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/tree.py
Labels: Bug, Performance

#1141 1112 testing and validation of queryprofiler object
  .github/workflows/ci.yaml
  .github/workflows/master-codecov.yml
  pytest.ini
  verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
  verticapy/tests_new/performance/__init__.py
  verticapy/tests_new/performance/vertica/__init__.py
  verticapy/tests_new/performance/vertica/test_qprof.py
  verticapy/tests_new/performance/vertica/test_tree.py
Labels: Unit Testing, Performance

#1157 Unit test report tolerance at metric level
  verticapy/tests_new/machine_learning/vertica/__init__.py
  verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py
  verticapy/tests_new/machine_learning/vertica/test_linear_model.py
  verticapy/tests_new/machine_learning/vertica/test_model_management.py
  verticapy/tests_new/machine_learning/vertica/test_tfidf.py
  verticapy/tests_new/machine_learning/vertica/test_tree_model.py
Labels: Unit Testing

#1165 Added code to overwrite the tree when Nan values are present
  verticapy/machine_learning/vertica/base.py
  verticapy/machine_learning/vertica/ensemble.py
Labels: Bug

#1164 Sphinx - tolerance page addition
  docs/source/contribution_guidelines.rst
  docs/source/tolerance.rst
Labels: Documentation

#1168 [QPROF] Correcting Bugs
  verticapy/__init__.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/qprof_utility.py
  verticapy/performance/vertica/tree.py
  verticapy/tests_new/performance/vertica/test_qprof.py
Labels: Performance

#1173 Qprof Interface Update + format_query
  verticapy/_utils/_sql/_format.py
  verticapy/performance/vertica/qprof.py
  verticapy/performance/vertica/qprof_interface.py
Labels: Enhancement
